### ISSUE TITLE
Run in Compose

### ISSUE THREAD

**Issue by onestix** [net-byte/socks5-server#7]
Hi @net-byte, thanks for this great container. Anyway I can run this also in compose? Cheers

**Comment by JsonSong89** [comment]
``` yml
version: "2.1"
services:
  heimdall:
    image: netbyte/socks5-server:latest
    container_name: socks5-server
    command: -l 0.0.0.0:1050 -u user -p psw
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    restart: unless-stopped
```
